// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1XTBBcTqdwqkla1pk_YX8ywOP6Y6EFvM',
    appId: '1:860785570975:web:457408e8995b3251725eaa',
    messagingSenderId: '860785570975',
    projectId: 'alpha-hedge-fund',
    authDomain: 'alpha-hedge-fund.firebaseapp.com',
    storageBucket: 'alpha-hedge-fund.appspot.com',
    measurementId: 'G-5WP9563F75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD5Utkm5lYLcUkNj7lt92a0n6oIpVL5j0',
    appId: '1:860785570975:android:8a6b1630d5ece628725eaa',
    messagingSenderId: '860785570975',
    projectId: 'alpha-hedge-fund',
    storageBucket: 'alpha-hedge-fund.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwPYA_EWHIj7h8kyqkkUAXGoVqo1zVtzI',
    appId: '1:860785570975:ios:e2678f6c0fd33ffc725eaa',
    messagingSenderId: '860785570975',
    projectId: 'alpha-hedge-fund',
    storageBucket: 'alpha-hedge-fund.appspot.com',
    iosClientId: '860785570975-pe8c3tq64m6ngti9lh03vf0jqblrgbgv.apps.googleusercontent.com',
    iosBundleId: 'dev.ditustudio.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwPYA_EWHIj7h8kyqkkUAXGoVqo1zVtzI',
    appId: '1:860785570975:ios:e2678f6c0fd33ffc725eaa',
    messagingSenderId: '860785570975',
    projectId: 'alpha-hedge-fund',
    storageBucket: 'alpha-hedge-fund.appspot.com',
    iosClientId: '860785570975-pe8c3tq64m6ngti9lh03vf0jqblrgbgv.apps.googleusercontent.com',
    iosBundleId: 'dev.ditustudio.flutterTemplate',
  );
}
